apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-automation

resources:
  - ./namespace.yaml
  - ./ghcr.yaml
  - ./mosquitto/ks.yaml
  - ./home-assistant/ks.yaml
#  - ./zigbee-house/ks.yaml
