apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: cert-manager-credentials
  namespace: cert-manager
spec:
  itemPath: "vaults/fmycvdzmeyvbndk7s7pjyrebtq/items/umbys4jfnh6k27u2isqdimhz6i"
